name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checks:
    name: Linters & Expo Doctor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run Prettier
        run: yarn linter-prettier
      - name: Run ESlint
        run: yarn eslint ${GITHUB_WORKSPACE}
      - name: Install Expo CLI dependency
        run: npm install -g expo-cli
      - name: Run Expo Doctor
        run: expo-cli doctor

