name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  checks:
    name: Run our checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Yarn install
        run: yarn install
      - name: Run Prettier Check
        run: yarn linter
      - name: Run Expo Doctor
        run: yarn expo-doctor

