name: Prettier

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  expo_doctor:
    name: Run prettier scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Yarn install
        run: yarn install
      - name: Run Prettier Check
        run: npx prettier --check .
        continue-on-error: true
